### ISSUE TITLE
Not working in popups

### ISSUE THREAD

**Issue by frnhr** [Microdisseny/django-ajax-raw-id-fields#3]
The app works great, even with inlines! One problem, though: it stops working in popups.

![Edit_list___urbandanish_solutions_and_New_Issue_·_Microdisseny_django-ajax-raw-id-fields_and_urdkroot___Volumes_Projects_urdkroot__-____pyenv_versions_urdkroot_lib_python3_6_site-packages_dj_ajax_raw_id_fields_static_dj_ajax_raw_id_fields_j](https://user-images.githubusercontent.com/1173748/59368559-d1de3400-8d3e-11e9-8474-849389e4fc7d.jpg)

Reason seems to be that there is no `#site-name` link rendered in the popup, which is where the JS code gets URL attribute from. This href is actually just `{% url 'admin:index' %}`, so I think we simply need a more robust way of sending this URL to the JS.

![DevTools_-_25_63_164_26_8000_admin_files_typedfile___to_field_id_filetype_5__filetype_id_5__popup_1](https://user-images.githubusercontent.com/1173748/59368828-56c94d80-8d3f-11e9-8e40-b6cab649bccc.jpg)

![view-source_25_63_164_26_8000_static_dj_ajax_raw_id_fields_js_dj_ajax_raw_id_fields_js](https://user-images.githubusercontent.com/1173748/59369001-bd4e6b80-8d3f-11e9-9ba6-937a76ac7d4e.jpg)

**Comment by abusquets** [comment]
Hi @frnhr,
I can you test version 0.2.1, please?
